# Generated by Django 4.2.4 on 2023-09-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_category_tag_alter_musician_options_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='albums.tag'),
        ),
    ]
