# Generated by Django 4.2.4 on 2023-10-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
